# Generated by Django 3.2.19 on 2024-03-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='relationship',
            field=models.CharField(choices=[('Partner', 'Partner'), ('Wife', 'Wife'), ('Husband', 'Husband'), ('Mother', 'Mother'), ('Girlfriend', 'Girlfriend'), ('Boyfriend', 'Boyfriend'), ('Father', 'Father'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Cousin', 'Cousin'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Friend', 'Friend'), ('Colleague', 'Colleague'), ('Boss', 'Boss'), ('Family Member', 'Family Member')], default='Partner', max_length=50),
        ),
    ]
