# Generated by Django 3.2.19 on 2024-03-08 13:29

import django.core.validators
from django.db import migrations, models
import partner_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=partner_profile.models.current_date, message='DOB cannot be in the future.')]),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='gender',
            field=models.CharField(default='Unspecified Gender', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='relationship',
            field=models.CharField(default='Partner', max_length=50),
        ),
    ]
