# Generated by Django 3.2.19 on 2024-03-08 10:53

import django.core.validators
from django.db import migrations, models
import partner_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_profile', '0002_auto_20240308_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='gender',
            field=models.CharField(default='Unsepecified Gender', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='year_of_birth',
            field=models.IntegerField(blank=True, help_text='Please enter a four-digit year format.', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=partner_profile.models.current_year, message='Year of birth cannot be in the future.'), django.core.validators.MinValueValidator(limit_value=1000, message='Year must be a four-digit number.')]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='relationship',
            field=models.CharField(default='Partner', max_length=50),
        ),
    ]
