# Generated by Django 3.2.19 on 2024-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_profile', '0003_auto_20240308_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='gender',
            field=models.CharField(default='Unspecified Gender', max_length=50),
        ),
    ]
