# Generated by Django 3.2.19 on 2024-02-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_partner_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
